name: Validar Script SH

on:
  push:
    branches: [ main ]

jobs:
  shellcheck:
    name: Ejecutar ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Validar script.sh con ShellCheck
        run: shellcheck script.sh
